export const QUESTIONS_GET_QUESTION_FULFILLED = 'QUESTIONS_GET_QUESTION_FULFILLED';
export const QUESTIONS_GET_ANSWERS_FULFILLED = 'QUESTIONS_GET_ANSWERS_FULFILLED';
export const QUESTION_RESET = 'QUESTION_RESET';