export const QUESTIONS_GET_FULFILLED = 'QUESTIONS_GET_FULFILLED';
export const QUESTIONS_PANEL_QUESTIONS_GET_FULFILLED = 'QUESTIONS_PANEL_QUESTIONS_GET_FULFILLED';
export const QUESTIONS_PANEL_RESET = 'QUESTIONS_PANEL_RESET';
export const QUESTIONS_RESET = 'QUESTIONS_RESET';